CHANGELOG.txt
cloudify_configuration/examples/simple.yaml
cloudify_custom_workflow/examples/example.yaml
cloudify_deployment_proxy/examples/deployment-proxy-custom-workflow.yaml
cloudify_deployment_proxy/examples/deployment-proxy-reuse.yaml
cloudify_deployment_proxy/examples/deployment-proxy.yaml
cloudify_deployment_proxy/examples/deployment-without-workflow.yaml
cloudify_deployment_proxy/examples/node-instance-proxy.yaml
cloudify_files/examples/blueprint.yaml
cloudify_files/examples/openstack-blueprint.yaml
cloudify_ssh_key/examples/create-secret-agent-key.yaml
cloudify_ssh_key/examples/import-simple-manager.yaml
cloudify_ssh_key/examples/ssh-key-blueprint.yaml
cloudify_suspend/examples/example.yaml
cloudify_terminal/examples/cisco.yaml
cloudify_terminal/examples/fortigate.yaml
cloudify_terminal/examples/linux-ssh.yaml
cloudify_terminal/tasks.py
plugin.yaml
setup.py

We have such error:
in line:
```python
ip_list = terminal_auth.get('ip', [ctx.instance.host_ip])
```
RuntimeError: Workflow failed: Task failed 'cloudify_terminal.tasks.run' -> host_id missing

Fix regression with ip's

---

README.md
cloudify_deployment_proxy/polling.py
cloudify_deployment_proxy/tests/client_mock.py
cloudify_deployment_proxy/tests/test_polling.py

Break on empty events list

---

cloudify_terminal/tasks.py

This pull request is fixing connection problems where host is not fully booted and plugin tries to access it. There's socket.timeout then which wasn't captured.

Socket timeout fix

---

cloudify_terminal/tasks.py

Potential security vulnerability with info logging as template can contain passwords. Changed it to debug.

Fixing logging levels

---

CHANGELOG.txt
README.md
cloudify_suspend/README.md
cloudify_suspend/tests/test_backups.py
cloudify_suspend/tests/test_statistics.py
cloudify_suspend/tests/test_suspend.py
cloudify_suspend/workflows.py
cloudify_terminal/README.md
cloudify_terminal/examples/cisco_flash_list.yaml
cloudify_terminal/terminal_connection.py
cloudify_terminal/tests/test_terminal_connection.py
plugin.yaml
setup.py

Backup/Restore workflows
Close connection after error in terminal plugin.

Backup workflow

---

cloudify_rest/rest_sdk/utility.py

Fixed typo and retain backward compatibility

Fixed typo

---

cloudify_scalelist/workflows.py

Reverts cloudify-incubator/cloudify-utilities-plugin#160

Revert "scalelist: wait for running tasks before calling _uninstall"

---

CHANGELOG.txt
cloudify_rest/examples/example-7-blueprint.yaml
cloudify_rest/examples/templates/create-user-precoded-1.yaml
cloudify_rest/examples/templates/create-user-precoded-2.yaml
cloudify_rest/examples/templates/create-user-precoded-3.json
cloudify_rest/examples/templates/create-user-precoded-3.yaml
cloudify_rest/tasks.py
cloudify_rest/tests/test_sdk.py
constraints.txt
dev-requirements.txt
plugin.yaml
setup.py
tox.ini

* Support raw_payload in rest sdk
* Support hardcoded translation_format version in rest sdk
* Support prerender template in rest sdk

Update to use SDK==0.0.4

---

CHANGELOG.txt
cloudify_files/__init__.py
cloudify_rest/README.md
cloudify_rest/tasks.py
cloudify_rest/tests/test_plugin.py
dev-requirements.txt
plugin.yaml
setup.py

update sudo again
use call method
move 1.12.6 changes to 1.13.0

bump version

---

CHANGELOG.txt
cloudify_cloudinit/__init__.py
cloudify_configuration/tasks.py
cloudify_deployment_proxy/__init__.py
cloudify_deployment_proxy/polling.py
cloudify_deployment_proxy/tests/test_blueprints.py
cloudify_deployment_proxy/tests/test_deployments.py
cloudify_deployment_proxy/tests/test_execute.py
cloudify_deployment_proxy/tests/test_polling.py
cloudify_deployment_proxy/utils.py
cloudify_files/__init__.py
cloudify_files/tests/test_cloudify_files.py
cloudify_rest/tests/test_plugin.py
cloudify_scalelist/workflows.py
cloudify_secrets/sdk.py
cloudify_secrets/tasks.py
cloudify_ssh_key/operations.py
cloudify_ssh_key/tests/test_key.py
cloudify_terminal/tasks.py
cloudify_terminal/tests/test_terminal_connection.py
constraints.txt
dev-requirements.txt
plugin.yaml
setup.py
test-requirements.txt
tox.ini

Fix syntax errors related to python3, partially checked with cloudify-common===5.0.1

Use updated version of namespaced package importer

---

.circleci/config.yml
CHANGELOG.txt
cloudify_cloudinit/__init__.py
cloudify_cloudinit/tasks.py
cloudify_cloudinit/tests/test_cloud_init.py
cloudify_cloudinit/tests/test_tasks.py
cloudify_rest/README.md
cloudify_rest/__init__.py
cloudify_rest/examples/example-1-blueprint.yaml
cloudify_rest/examples/example-2-blueprint.yaml
cloudify_rest/examples/example-3-blueprint.yaml
cloudify_rest/examples/example-5-blueprint.yaml
cloudify_rest/examples/example-6-blueprint.yaml
cloudify_rest/examples/example-7-blueprint.yaml
cloudify_rest/examples/example-8-blueprint.yaml
cloudify_rest/examples/templates/create-user-post-template.yaml
cloudify_rest/tasks.py
cloudify_rest/tests/test_plugin.py
cloudify_rest/tests/test_tasks.py
cloudify_terminal/README.md
cloudify_terminal/__init__.py
cloudify_terminal/examples/cisco.yaml
cloudify_terminal/examples/cisco_flash_list.yaml
cloudify_terminal/examples/fortigate.yaml
cloudify_terminal/examples/linux-ssh.yaml
cloudify_terminal/tasks.py
cloudify_terminal/tests/test_tasks.py
constraints.txt
plugin.yaml
setup.py

* Add resumable flag support
* add certificate support for rest verify field

CYBL-1006: Rest resumable support

---

CHANGELOG.txt
cloudify_hooks_workflow/README.md
cloudify_hooks_workflow/tasks.py
cloudify_hooks_workflow/tests/test_tasks.py
cloudify_rest/README.md
cloudify_rest/examples/example-1-blueprint.yaml
cloudify_rest/tasks.py
cloudify_rest/tests/test_tasks.py
cloudify_terminal/tasks.py
plugin.yaml
setup.py

Reverts cloudify-incubator/cloudify-utilities-plugin#195

Revert "Rest: hooks api support"

---

plugin.yaml
setup.py

Use updated obfuscate_passwords from cloudify-utilities-plugins-sdk.

CY-2757 Obfuscate passwords, secrets and tokens

---

CHANGELOG.txt
cloudify_terminal/tests/test_terminal_connection.py
plugin.yaml
setup.py

bump utilities plugin to use cloudify-utilities-plugins-sdk==0.0.33 with terminal encoding changes

RD-278-Bump-Version

---

CHANGELOG.txt
cloudify_files/__init__.py
plugin.yaml

Related to: https://cloudifysource.atlassian.net/browse/CYBL-1207

fixed mode property of cloudify.nodes.File

---

CHANGELOG.txt
cloudify_resources/README.md
cloudify_resources/tasks.py
plugin.yaml

https://cloudifysource.atlassian.net/browse/CYBL-1570

extended cloudify_resources plugin

---

CHANGELOG.txt
cloudify_scalelist/workflows.py
plugin.yaml
plugin_1_4.yaml
v2_plugin.yaml

https://cloudifysource.atlassian.net/browse/CYBL-1871

add rollback_on_failure flag to scalelist plugin

---

CHANGELOG.txt
cloudify_scalelist/workflows.py
plugin.yaml
plugin_1_4.yaml
v2_plugin.yaml

https://cloudifysource.atlassian.net/browse/CYBL-1872

added force_remove flag to scaledownlist

---

cloudify_terminal/__init__.py

This is just a stylistic change - feel free to adapt it to your needs/tests.
This just looked a bit strange in our logs.

[F5] Fixed a typo that was visible in our cloudify-manager UI's logs.

---

CHANGELOG.txt
cloudify_cloudinit/__version__.py
plugin.yaml
plugin_1_4.yaml
plugin_1_5.yaml
v2_plugin.yaml

remove-blueprint-type-override.
type already part of cloudify standard types https://github.com/cloudify-cosmo/cloudify-manager/blob/master/resources/rest-service/cloudify/types/types.yaml#L1303

remove-blueprint-type-override
